import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from '@/components/common/navbar';
import {ClerkProvider} from "@clerk/nextjs";
import {Footer} from '@/components/common/footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
       
        <body>
        <Header />
          {children}
          <Footer />
          
        </body>

      </html>
      </ClerkProvider>
  )
}
